// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Uses the same layered loader as the app, so the Prisma CLI always targets
// the same database the server would. `APP_ENV=production npm run db:deploy`
// runs migrations against production; unset, everything targets dev.
import "./src/config/loadEnv.js";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI / Migrate use the DIRECT connection (port 5432) — migrations
    // cannot run over the PgBouncer transaction pooler. The runtime client uses
    // the pooled DATABASE_URL via a driver adapter passed to PrismaClient.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
